### ISSUE TITLE
Bug in DispatchTimeInterval.toSeconds()

### ISSUE THREAD

**Issue by alexandergriekspoor** [mattgallagher/CwlUtils#12]
After a lot of head scratching earlier today I found the cause of some unexpected timer behaviour originating in code I originally copied from your DispatchTimeInterval.toSeconds() extension. The bug still seems to be there, calculations here are not correct:

https://github.com/mattgallagher/CwlUtils/blob/ddeb12d34e1b45cc3cc4c0020319f62770da3c1a/Sources/CwlUtils/CwlDispatch.swift#L112

```
(lldb) po DispatchTimeInterval.milliseconds(1).toSeconds()
9.9999999999999995e-07
(lldb) po DispatchTimeInterval.microseconds(1).toSeconds()
0.001
```

I opted by changing the relevant cases in the switch: 

```
case .milliseconds, .microseconds, .nanoseconds:
            return (1.0 / Double(NSEC_PER_SEC)) * Double(toNanoseconds())
```

Thanks for sharing CwlUtils!

**Comment by mattgallagher** [comment]
This is embarrassing: I must have misread NSEC_PER_MSEC as MSEC_PER_SEC, that's the only way my broken logic would make sense. Of course, this bug existed because there were no tests for these functions.

I've added tests and fixed the broken behavior in the latest commit:

https://github.com/mattgallagher/CwlUtils/commit/7ce81b873e938d8ba6b04006bc433ddcd42e008b

Thanks for helping out.
