### ISSUE TITLE
osRev crashes

### ISSUE THREAD

**Issue by asutula** [mattgallagher/CwlUtils#16]
I'm testing this in iOS 11.2.1. When osRev is queried, `preFlightResult` is equal to `-1` and a `POSIXErrorCode` is thrown. It's not clear to me how to debug this further.

**Comment by mattgallagher** [comment]
Thanks for reporting this. I'll look into it later today.

**Comment by vsanthanam** [comment]
The documentation says that `osRev` is not available in iOS. Am I misunderstanding this?

**Comment by mattgallagher** [comment]
@vsanthanam That's correct. When you try to fetch [CTL_KERN, KERN_OSREV] from sysctl on an iOS device, an EPERM error occurs (setting not permitted or available). It works in the simulator which is why the problem went undetected for a while.

I've put conditionals around the osRev accessor to keep it macOS only. If you need an iOS build number, use `Sysctl.osVersion` or `ProcessInfo.processInfo.operatingSystemVersion`.

**Comment by asutula** [comment]
Sounds like the right fix. Thanks!
