### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by gdahilig** [mattgallagher/CwlUtils#21]
During my initial build after integrating CwlUtils using CocoaPods. 
Environment:

- Xcode Version 10.1 (10B61)
- macOS Mojave V.10.13.2 (18C54)

Here is the build output from Xcode:
![screenshot](https://user-images.githubusercontent.com/1619435/51714419-fd5bbe80-1fe9-11e9-8e69-ea8cb71d439a.png)

**Comment by mattgallagher** [comment]
Hi Gene,

What you're seeing here is a bug in Cocoapods 1.5.x when targetting macOS. The bug is described here:

https://github.com/CocoaPods/CocoaPods/issues/7708

To work around the bug you must either:

* Update Cocoapods to 1.6 (currently at beta 2) by running `sudo gem install cocoapods --pre` at a command prompt

OR, if you're not happy running Cocoapods beta:

* Apply the User Defined Settings changes described in this comment on the issue:

https://github.com/CocoaPods/CocoaPods/issues/7708#issuecomment-424392893
