### ISSUE TITLE
CwlSysctl: adding structFromSysctl or intArrayFromSysctl

### ISSUE THREAD

**Issue by nyg** [mattgallagher/CwlUtils#9]
Hello!

First of all, thanks for making CwlSysctl! Great tool :).

I wrote two helper functions that could be useful: one to convert the result of your sysctl into a struct and the other into an array of Int64. My goal was to be able to retrieve the result of `sysctl kernel.boottime`.

I have no idea if the following code is the correct way to do it, or if it can be improved... I usually don't go that "far" down the rabbit hole :).

```swift
public func structFromSysctl<S>(levels: Int32..., as: S.Type = S.self) throws -> S {

    let buffer = try sysctl(levels: levels)

    return buffer.withUnsafeBytes() {
        $0.load(as: S.self)
    }
}
```

Usage:

```swift
let bootTime = try structFromSysctl(levels: CTL_KERN, KERN_BOOTTIME, as: timeval.self) // or
let bootTime: timeval = try structFromSysctl(levels: CTL_KERN, KERN_BOOTTIME)
print(bootTime) // timeval(tv_sec: 1499259206, tv_usec: 122778)
```

And for Int64 arrays:

```swift
public func intArrayFromSysctl(levels: Int32...) throws -> [Int64] {

    let buffer = try sysctl(levels: levels)

    if buffer.count % 8 != 0 {
        throw SysctlError.invalidSize
    }

    return buffer.withUnsafeBytes { pointer in
        (0..<(buffer.count / 8)).map { i in
            pointer.load(fromByteOffset: i * 8, as: Int64.self)
        }
    }
}
```

```swift
let bootTime = try intArrayFromSysctl(levels: CTL_KERN, KERN_BOOTTIME)
print(bootTime) // [1499259206, 122778]
```

I can submit a pull request if my solution is acceptable.

**Comment by mattgallagher** [comment]
Your issue made me go back and look at the Sysctl implementation. With the exception of the convenience accessors on Sysctl... the interface wasn't well considered.

I've refactored the interface so that everything is on the Sysctl struct. The old `int` accessors are gone, replaced by `valueOfType(_:forKey:)`. This same function can be used for returning structs or other types. This lets you solve your `KERN_BOOTTIME` scenario as follows:

    let bootTime = try! Sysctl.valueOfType(timeval.self, forKeys: CTL_KERN, KERN_BOOTTIME)

Let me know if this makes sense or if it doesn't really solve your problem and we can revisit.

**Comment by nyg** [comment]
Great! That's much better, thanks.
